/* 
 * English layout for smart-tv-keyboard
 * Denys Petrovnin <dipcore@gmail.com>
 * Date: 17-May-2015 11:16:22 PM
 */
smartTvKeyboardLayouts = typeof smartTvKeyboardLayouts === 'undefined'? {} : smartTvKeyboardLayouts;
smartTvKeyboardLayouts.en = {
    unshift: [
    	[
            {text: '`', value: '`', length: 1, color: 'letter'},
            {text: '1', value: '1', length: 1, color: 'letter'},
            {text: '2', value: '2', length: 1, color: 'letter'},
            {text: '3', value: '3', length: 1, color: 'letter'},
            {text: '4', value: '4', length: 1, color: 'letter'},
            {text: '5', value: '5', length: 1, color: 'letter'},
            {text: '6', value: '6', length: 1, color: 'letter'},
            {text: '7', value: '7', length: 1, color: 'letter'},
            {text: '8', value: '8', length: 1, color: 'letter'},
            {text: '9', value: '9', length: 1, color: 'letter'},
            {text: '0', value: '0', length: 1, color: 'letter'},
            {text: '-', value: '-', length: 1, color: 'letter'},
            {text: '=', value: '=', length: 1, color: 'letter'},
            {text: 'Clear', value: '&&clear', length: 2, color: 'danger'}
        ],
        [
            {text: 'q', value: 'q', length: 1, color: 'letter'},
            {text: 'w', value: 'w', length: 1, color: 'letter'},
            {text: 'e', value: 'e', length: 1, color: 'letter'},
            {text: 'r', value: 'r', length: 1, color: 'letter'},
            {text: 't', value: 't', length: 1, color: 'letter'},
            {text: 'y', value: 'y', length: 1, color: 'letter'},
            {text: 'u', value: 'u', length: 1, color: 'letter'},
            {text: 'i', value: 'i', length: 1, color: 'letter'},
            {text: 'o', value: 'o', length: 1, color: 'letter'},
            {text: 'p', value: 'p', length: 1, color: 'letter'},
            {text: '[', value: '[', length: 1, color: 'letter'},
            {text: ']', value: ']', length: 1, color: 'letter'},
            {text: '\\', value: '\\', length: 1, color: 'letter'},
            {text: 'Back', value: '&&back', length: 2, color: 'danger'}
        ],
        [
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'a', value: 'a', length: 1, color: 'letter'},
            {text: 's', value: 's', length: 1, color: 'letter'},
            {text: 'd', value: 'd', length: 1, color: 'letter'},
            {text: 'f', value: 'f', length: 1, color: 'letter'},
            {text: 'g', value: 'g', length: 1, color: 'letter'},
            {text: 'h', value: 'h', length: 1, color: 'letter'},
            {text: 'j', value: 'j', length: 1, color: 'letter'},
            {text: 'k', value: 'k', length: 1, color: 'letter'},
            {text: 'l', value: 'l', length: 1, color: 'letter'},
            {text: ';', value: ';', length: 1, color: 'letter'},
            {text: '\'', value: '\'', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Enter', value: '&&enter', length: 2, color: 'success'}
        ],
        [
            {text: 'abc', value: '&&switchMode', length: 2, color: 'toggle'},
            {text: 'z', value: 'z', length: 1, color: 'letter'},
            {text: 'x', value: 'x', length: 1, color: 'letter'},
            {text: 'c', value: 'c', length: 1, color: 'letter'},
            {text: 'v', value: 'v', length: 1, color: 'letter'},
            {text: 'b', value: 'b', length: 1, color: 'letter'},
            {text: 'n', value: 'n', length: 1, color: 'letter'},
            {text: 'm', value: 'm', length: 1, color: 'letter'},
            {text: ',', value: ',', length: 1, color: 'letter'},
            {text: '.', value: '.', length: 1, color: 'letter'},
            {text: '/', value: '/', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '<', value: '&&cursorMoveLeft', length: 1, color: 'navigation'},
            {text: '>', value: '&&cursorMoveRight', length: 1, color: 'navigation'}
        ],
        [
            {text: 'Eng', value: '&&switchLanguage', length: 2, color: 'toggle'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Space', value: ' ', length: 6, color: 'letter'},
            {text: '', value: ';', length: 1, color: 'disabled'},
            {text: '', value: '/', length: 1, color: 'disabled'},
            {text: '', value: ' ', length: 1, color: 'disabled'},
            {text: 'Cancel', value: '&&cancel', length: 2, color: 'warning'}
        ]
    ],
    shift: [
        [
            {text: '~', value: '~', length: 1, color: 'letter'},
            {text: '!', value: '!', length: 1, color: 'letter'},
            {text: '@', value: '@', length: 1, color: 'letter'},
            {text: '#', value: '#', length: 1, color: 'letter'},
            {text: '$', value: '$', length: 1, color: 'letter'},
            {text: '%', value: '%', length: 1, color: 'letter'},
            {text: '^', value: '^', length: 1, color: 'letter'},
            {text: '&', value: '&', length: 1, color: 'letter'},
            {text: '*', value: '*', length: 1, color: 'letter'},
            {text: '(', value: '(', length: 1, color: 'letter'},
            {text: ')', value: ')', length: 1, color: 'letter'},
            {text: '_', value: '_', length: 1, color: 'letter'},
            {text: '+', value: '+', length: 1, color: 'letter'},
            {text: 'Clear', value: '&&clear', length: 2, color: 'danger'}
        ],
        [
            {text: 'Q', value: 'Q', length: 1, color: 'letter'},
            {text: 'W', value: 'W', length: 1, color: 'letter'},
            {text: 'E', value: 'E', length: 1, color: 'letter'},
            {text: 'R', value: 'R', length: 1, color: 'letter'},
            {text: 'T', value: 'T', length: 1, color: 'letter'},
            {text: 'Y', value: 'Y', length: 1, color: 'letter'},
            {text: 'U', value: 'U', length: 1, color: 'letter'},
            {text: 'I', value: 'I', length: 1, color: 'letter'},
            {text: 'O', value: 'O', length: 1, color: 'letter'},
            {text: 'P', value: 'P', length: 1, color: 'letter'},
            {text: '{', value: '{', length: 1, color: 'letter'},
            {text: '}', value: '}', length: 1, color: 'letter'},
            {text: '|', value: '|', length: 1, color: 'letter'},
            {text: 'Back', value: '&&back', length: 2, color: 'danger'}
        ],
        [
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'A', value: 'A', length: 1, color: 'letter'},
            {text: 'S', value: 'S', length: 1, color: 'letter'},
            {text: 'D', value: 'D', length: 1, color: 'letter'},
            {text: 'F', value: 'F', length: 1, color: 'letter'},
            {text: 'G', value: 'G', length: 1, color: 'letter'},
            {text: 'H', value: 'H', length: 1, color: 'letter'},
            {text: 'J', value: 'J', length: 1, color: 'letter'},
            {text: 'K', value: 'K', length: 1, color: 'letter'},
            {text: 'L', value: 'L', length: 1, color: 'letter'},
            {text: ':', value: ':', length: 1, color: 'letter'},
            {text: '"', value: '"', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Enter', value: '&&enter', length: 2, color: 'success'}
        ],
        [
            {text: 'ABC', value: '&&switchMode', length: 2, color: 'toggle'},
            {text: 'Z', value: 'Z', length: 1, color: 'letter'},
            {text: 'X', value: 'X', length: 1, color: 'letter'},
            {text: 'C', value: 'C', length: 1, color: 'letter'},
            {text: 'V', value: 'V', length: 1, color: 'letter'},
            {text: 'B', value: 'B', length: 1, color: 'letter'},
            {text: 'N', value: 'N', length: 1, color: 'letter'},
            {text: 'M', value: 'M', length: 1, color: 'letter'},
            {text: '<', value: '<', length: 1, color: 'letter'},
            {text: '>', value: '>', length: 1, color: 'letter'},
            {text: '?', value: '?', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '<', value: '&&cursorMoveLeft', length: 1, color: 'navigation'},
            {text: '>', value: '&&cursorMoveRight', length: 1, color: 'navigation'}
        ],
        [
            {text: 'Eng', value: '&&switchLanguage', length: 2, color: 'toggle'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Space', value: ' ', length: 6, color: 'letter'},
            {text: '', value: ';', length: 1, color: 'disabled'},
            {text: '', value: '/', length: 1, color: 'disabled'},
            {text: '', value: ' ', length: 1, color: 'disabled'},
            {text: 'Cancel', value: '&&cancel', length: 2, color: 'warning'}
        ]
    ],
    symb: [
        [
            {text: '`', value: '`', length: 1, color: 'letter'},
            {text: '1', value: '1', length: 1, color: 'letter'},
            {text: '2', value: '2', length: 1, color: 'letter'},
            {text: '3', value: '3', length: 1, color: 'letter'},
            {text: '4', value: '4', length: 1, color: 'letter'},
            {text: '5', value: '5', length: 1, color: 'letter'},
            {text: '6', value: '6', length: 1, color: 'letter'},
            {text: '7', value: '7', length: 1, color: 'letter'},
            {text: '8', value: '8', length: 1, color: 'letter'},
            {text: '9', value: '9', length: 1, color: 'letter'},
            {text: '0', value: '0', length: 1, color: 'letter'},
            {text: '-', value: '-', length: 1, color: 'letter'},
            {text: '=', value: '=', length: 1, color: 'letter'},
            {text: 'Clear', value: '&&clear', length: 2, color: 'danger'}
        ],
        [
            {text: '/', value: '/', length: 1, color: 'letter'},
            {text: '^', value: '^', length: 1, color: 'letter'},
            {text: '~', value: '~', length: 1, color: 'letter'},
            {text: '?', value: '?', length: 1, color: 'letter'},
            {text: '!', value: '!', length: 1, color: 'letter'},
            {text: '\'', value: '\'', length: 1, color: 'letter'},
            {text: '\"', value: '\"', length: 1, color: 'letter'},
            {text: '(', value: '(', length: 1, color: 'letter'},
            {text: ')', value: ')', length: 1, color: 'letter'},
            {text: ':', value: ':', length: 1, color: 'letter'},
            {text: ';', value: ';', length: 1, color: 'letter'},
            {text: '+', value: '+', length: 1, color: 'letter'},
            {text: '&', value: '&', length: 1, color: 'letter'},
            {text: 'Back', value: '&&back', length: 2, color: 'danger'}
        ],
        [
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '%', value: '%', length: 1, color: 'letter'},
            {text: '*', value: '*', length: 1, color: 'letter'},
            {text: '<', value: '<', length: 1, color: 'letter'},
            {text: '>', value: '>', length: 1, color: 'letter'},
            {text: '[', value: '[', length: 1, color: 'letter'},
            {text: ']', value: ']', length: 1, color: 'letter'},
            {text: '{', value: '{', length: 1, color: 'letter'},
            {text: '}', value: '}', length: 1, color: 'letter'},
            {text: ',', value: ',', length: 1, color: 'letter'},
            {text: '§', value: '§', length: 1, color: 'letter'},
            {text: '#', value: '#', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Enter', value: '&&enter', length: 2, color: 'success'}
        ],
        [
            {text: '123;)', value: '&&switchMode', length: 2, color: 'toggle'},
            {text: '¿', value: '¿', length: 1, color: 'letter'},
            {text: '£', value: '£', length: 1, color: 'letter'},
            {text: '¥', value: '¥', length: 1, color: 'letter'},
            {text: '＼', value: '＼', length: 1, color: 'letter'},
            {text: '|', value: '|', length: 1, color: 'letter'},
            {text: '.', value: '.', length: 1, color: 'letter'},
            {text: '@', value: '@', length: 1, color: 'letter'},
            {text: '_', value: '_', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '<', value: '&&cursorMoveLeft', length: 1, color: 'navigation'},
            {text: '>', value: '&&cursorMoveRight', length: 1, color: 'navigation'}
        ],
        [
            {text: 'Eng', value: '&&switchLanguage', length: 2, color: 'toggle'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Space', value: ' ', length: 6, color: 'letter'},
            {text: '', value: ';', length: 1, color: 'disabled'},
            {text: '', value: '/', length: 1, color: 'disabled'},
            {text: '', value: ' ', length: 1, color: 'disabled'},
            {text: 'Cancel', value: '&&cancel', length: 2, color: 'warning'}
        ]
    ]
};
