/* 
 * Russian layout for smart-tv-keyboard
 * Denys Petrovnin <dipcore@gmail.com>
 * Date: 17-May-2015 11:17:48 PM
 */
smartTvKeyboardLayouts = typeof smartTvKeyboardLayouts === 'undefined'? {} : smartTvKeyboardLayouts;
smartTvKeyboardLayouts.ru = {
    unshift: [
        [
            {text: '`', value: '`', length: 1, color: 'letter'},
            {text: '1', value: '1', length: 1, color: 'letter'},
            {text: '2', value: '2', length: 1, color: 'letter'},
            {text: '3', value: '3', length: 1, color: 'letter'},
            {text: '4', value: '4', length: 1, color: 'letter'},
            {text: '5', value: '5', length: 1, color: 'letter'},
            {text: '6', value: '6', length: 1, color: 'letter'},
            {text: '7', value: '7', length: 1, color: 'letter'},
            {text: '8', value: '8', length: 1, color: 'letter'},
            {text: '9', value: '9', length: 1, color: 'letter'},
            {text: '0', value: '0', length: 1, color: 'letter'},
            {text: '-', value: '-', length: 1, color: 'letter'},
            {text: '=', value: '=', length: 1, color: 'letter'},
            {text: 'Clear', value: '&&clear', length: 2, color: 'danger'}
        ],
        [
            {text: 'й', value: 'й', length: 1, color: 'letter'},
            {text: 'ц', value: 'ц', length: 1, color: 'letter'},
            {text: 'у', value: 'у', length: 1, color: 'letter'},
            {text: 'к', value: 'к', length: 1, color: 'letter'},
            {text: 'е', value: 'е', length: 1, color: 'letter'},
            {text: 'н', value: 'н', length: 1, color: 'letter'},
            {text: 'г', value: 'г', length: 1, color: 'letter'},
            {text: 'ш', value: 'ш', length: 1, color: 'letter'},
            {text: 'щ', value: 'щ', length: 1, color: 'letter'},
            {text: 'з', value: 'з', length: 1, color: 'letter'},
            {text: '[', value: '[', length: 1, color: 'letter'},
            {text: ']', value: ']', length: 1, color: 'letter'},
            {text: '\\', value: '\\', length: 1, color: 'letter'},
            {text: 'Back', value: '&&back', length: 2, color: 'danger'}
        ],
        [
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'ф', value: 'ф', length: 1, color: 'letter'},
            {text: 'ы', value: 'ы', length: 1, color: 'letter'},
            {text: 'в', value: 'в', length: 1, color: 'letter'},
            {text: 'а', value: 'а', length: 1, color: 'letter'},
            {text: 'п', value: 'п', length: 1, color: 'letter'},
            {text: 'р', value: 'р', length: 1, color: 'letter'},
            {text: 'о', value: 'о', length: 1, color: 'letter'},
            {text: 'л', value: 'л', length: 1, color: 'letter'},
            {text: 'д', value: 'д', length: 1, color: 'letter'},
            {text: ';', value: ';', length: 1, color: 'letter'},
            {text: '\'', value: '\'', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Enter', value: '&&enter', length: 2, color: 'success'}
        ],
        [
            {text: 'abc', value: '&&switchMode', length: 2, color: 'toggle'},
            {text: 'я', value: 'я', length: 1, color: 'letter'},
            {text: 'ч', value: 'ч', length: 1, color: 'letter'},
            {text: 'с', value: 'с', length: 1, color: 'letter'},
            {text: 'м', value: 'м', length: 1, color: 'letter'},
            {text: 'и', value: 'и', length: 1, color: 'letter'},
            {text: 'т', value: 'т', length: 1, color: 'letter'},
            {text: 'ь', value: 'ь', length: 1, color: 'letter'},
            {text: ',', value: ',', length: 1, color: 'letter'},
            {text: '.', value: '.', length: 1, color: 'letter'},
            {text: '/', value: '/', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '<', value: '&&cursorMoveLeft', length: 1, color: 'navigation'},
            {text: '>', value: '&&cursorMoveRight', length: 1, color: 'navigation'}
        ],
        [
            {text: 'Rus', value: '&&switchLanguage', length: 2, color: 'toggle'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Space', value: ' ', length: 6, color: 'letter'},
            {text: '', value: ';', length: 1, color: 'disabled'},
            {text: '', value: '/', length: 1, color: 'disabled'},
            {text: '', value: ' ', length: 1, color: 'disabled'},
            {text: 'Cancel', value: '&&cancel', length: 2, color: 'warning'}
        ]
    ],
    shift: [
        [
            {text: '~', value: '~', length: 1, color: 'letter'},
            {text: '!', value: '!', length: 1, color: 'letter'},
            {text: '@', value: '@', length: 1, color: 'letter'},
            {text: '#', value: '#', length: 1, color: 'letter'},
            {text: '$', value: '$', length: 1, color: 'letter'},
            {text: '%', value: '%', length: 1, color: 'letter'},
            {text: '^', value: '^', length: 1, color: 'letter'},
            {text: '&', value: '&', length: 1, color: 'letter'},
            {text: '*', value: '*', length: 1, color: 'letter'},
            {text: '(', value: '(', length: 1, color: 'letter'},
            {text: ')', value: ')', length: 1, color: 'letter'},
            {text: '_', value: '_', length: 1, color: 'letter'},
            {text: '+', value: '+', length: 1, color: 'letter'},
            {text: 'Clear', value: '&&clear', length: 2, color: 'danger'}
        ],
        [
            {text: 'Й', value: 'Й', length: 1, color: 'letter'},
            {text: 'Ц', value: 'Ц', length: 1, color: 'letter'},
            {text: 'У', value: 'У', length: 1, color: 'letter'},
            {text: 'К', value: 'К', length: 1, color: 'letter'},
            {text: 'Е', value: 'Е', length: 1, color: 'letter'},
            {text: 'Н', value: 'Н', length: 1, color: 'letter'},
            {text: 'Г', value: 'Г', length: 1, color: 'letter'},
            {text: 'Ш', value: 'Ш', length: 1, color: 'letter'},
            {text: 'Щ', value: 'Щ', length: 1, color: 'letter'},
            {text: 'З', value: 'З', length: 1, color: 'letter'},
            {text: '{', value: '{', length: 1, color: 'letter'},
            {text: '}', value: '}', length: 1, color: 'letter'},
            {text: '|', value: '|', length: 1, color: 'letter'},
            {text: 'Back', value: '&&back', length: 2, color: 'danger'}
        ],
        [
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Ф', value: 'Ф', length: 1, color: 'letter'},
            {text: 'Ы', value: 'Ы', length: 1, color: 'letter'},
            {text: 'В', value: 'В', length: 1, color: 'letter'},
            {text: 'А', value: 'А', length: 1, color: 'letter'},
            {text: 'П', value: 'П', length: 1, color: 'letter'},
            {text: 'Р', value: 'Р', length: 1, color: 'letter'},
            {text: 'О', value: 'О', length: 1, color: 'letter'},
            {text: 'Л', value: 'Л', length: 1, color: 'letter'},
            {text: 'Д', value: 'Д', length: 1, color: 'letter'},
            {text: ':', value: ':', length: 1, color: 'letter'},
            {text: '"', value: '"', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Enter', value: '&&enter', length: 2, color: 'success'}
        ],
        [
            {text: 'ABC', value: '&&switchMode', length: 2, color: 'toggle'},
            {text: 'Я', value: 'Я', length: 1, color: 'letter'},
            {text: 'Ч', value: 'Ч', length: 1, color: 'letter'},
            {text: 'С', value: 'С', length: 1, color: 'letter'},
            {text: 'М', value: 'М', length: 1, color: 'letter'},
            {text: 'И', value: 'И', length: 1, color: 'letter'},
            {text: 'Т', value: 'Т', length: 1, color: 'letter'},
            {text: 'Ь', value: 'Ь', length: 1, color: 'letter'},
            {text: '<', value: '<', length: 1, color: 'letter'},
            {text: '>', value: '>', length: 1, color: 'letter'},
            {text: '?', value: '?', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '<', value: '&&cursorMoveLeft', length: 1, color: 'navigation'},
            {text: '>', value: '&&cursorMoveRight', length: 1, color: 'navigation'}
        ],
        [
            {text: 'Eng', value: '&&switchLanguage', length: 2, color: 'toggle'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Space', value: ' ', length: 6, color: 'letter'},
            {text: '', value: ';', length: 1, color: 'disabled'},
            {text: '', value: '/', length: 1, color: 'disabled'},
            {text: '', value: ' ', length: 1, color: 'disabled'},
            {text: 'Cancel', value: '&&cancel', length: 2, color: 'warning'}
        ]
    ],
    symb: [
        [
            {text: '`', value: '`', length: 1, color: 'letter'},
            {text: '1', value: '1', length: 1, color: 'letter'},
            {text: '2', value: '2', length: 1, color: 'letter'},
            {text: '3', value: '3', length: 1, color: 'letter'},
            {text: '4', value: '4', length: 1, color: 'letter'},
            {text: '5', value: '5', length: 1, color: 'letter'},
            {text: '6', value: '6', length: 1, color: 'letter'},
            {text: '7', value: '7', length: 1, color: 'letter'},
            {text: '8', value: '8', length: 1, color: 'letter'},
            {text: '9', value: '9', length: 1, color: 'letter'},
            {text: '0', value: '0', length: 1, color: 'letter'},
            {text: '-', value: '-', length: 1, color: 'letter'},
            {text: '=', value: '=', length: 1, color: 'letter'},
            {text: 'Clear', value: '&&clear', length: 2, color: 'danger'}
        ],
        [
            {text: '/', value: '/', length: 1, color: 'letter'},
            {text: '^', value: '^', length: 1, color: 'letter'},
            {text: '~', value: '~', length: 1, color: 'letter'},
            {text: '?', value: '?', length: 1, color: 'letter'},
            {text: '!', value: '!', length: 1, color: 'letter'},
            {text: '\'', value: '\'', length: 1, color: 'letter'},
            {text: '\"', value: '\"', length: 1, color: 'letter'},
            {text: '(', value: '(', length: 1, color: 'letter'},
            {text: ')', value: ')', length: 1, color: 'letter'},
            {text: ':', value: ':', length: 1, color: 'letter'},
            {text: ';', value: ';', length: 1, color: 'letter'},
            {text: '+', value: '+', length: 1, color: 'letter'},
            {text: '&', value: '&', length: 1, color: 'letter'},
            {text: 'Back', value: '&&back', length: 2, color: 'danger'}
        ],
        [
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '%', value: '%', length: 1, color: 'letter'},
            {text: '*', value: '*', length: 1, color: 'letter'},
            {text: '<', value: '<', length: 1, color: 'letter'},
            {text: '>', value: '>', length: 1, color: 'letter'},
            {text: '[', value: '[', length: 1, color: 'letter'},
            {text: ']', value: ']', length: 1, color: 'letter'},
            {text: '{', value: '{', length: 1, color: 'letter'},
            {text: '}', value: '}', length: 1, color: 'letter'},
            {text: ',', value: ',', length: 1, color: 'letter'},
            {text: '§', value: '§', length: 1, color: 'letter'},
            {text: '#', value: '#', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Enter', value: '&&enter', length: 2, color: 'success'}
        ],
        [
            {text: '123;)', value: '&&switchMode', length: 2, color: 'toggle'},
            {text: '¿', value: '¿', length: 1, color: 'letter'},
            {text: '£', value: '£', length: 1, color: 'letter'},
            {text: '¥', value: '¥', length: 1, color: 'letter'},
            {text: '＼', value: '＼', length: 1, color: 'letter'},
            {text: '|', value: '|', length: 1, color: 'letter'},
            {text: '.', value: '.', length: 1, color: 'letter'},
            {text: '@', value: '@', length: 1, color: 'letter'},
            {text: '_', value: '_', length: 1, color: 'letter'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '<', value: '&&cursorMoveLeft', length: 1, color: 'navigation'},
            {text: '>', value: '&&cursorMoveRight', length: 1, color: 'navigation'}
        ],
        [
            {text: 'Eng', value: '&&switchLanguage', length: 2, color: 'toggle'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: '', value: null, length: 1, color: 'disabled'},
            {text: 'Space', value: ' ', length: 6, color: 'letter'},
            {text: '', value: ';', length: 1, color: 'disabled'},
            {text: '', value: '/', length: 1, color: 'disabled'},
            {text: '', value: ' ', length: 1, color: 'disabled'},
            {text: 'Cancel', value: '&&cancel', length: 2, color: 'warning'}
        ]
    ]
};